# Pietro Customizations #
substitutions:
  device_name: basic-r4-03
  friendly_name: Spina Alloro
  ip_addres: 192.168.100.39
  platform: esp32
  board: esp32c3


# COMMON CONFIG
packages:
  common: !include packages/common-basic-r4.yaml

###################
## DEVICE CONFIG ##
###################

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO09
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    internal: True
    on_press:
      then:
        - switch.toggle: relay
  - platform: status
    name: Status
    internal: True

light:
  - platform: status_led
    id: blue_led
    internal: True
    pin:
      number: GPIO6
      inverted: True

switch:
  - platform: gpio
    name: None
    pin: GPIO4
    id: relay
    on_turn_off:
      if:
        condition:
          - light.is_on: blue_led
        then:
          - light.turn_off: blue_led
    