# Pietro Customizations #
substitutions:
  device_name: basic-r2-04
  friendly_name: Luce Letto
  ip_addres: 192.168.100.20
  platform: esp8266
  board: esp8285


# COMMON CONFIG
packages:
  common: !include packages/common.yaml


###################
## DEVICE CONFIG ##
###################

# OUTPUT che controlla il relè
output:
  - platform: gpio
    pin: GPIO12
    id: relay_output

# LIGHT che usa l'output (visto da Home Assistant come lampadina)
light:
  - platform: binary
    name: ""
    output: relay_output
    id: relay_1
    restore_mode: RESTORE_DEFAULT_OFF

# Pulsante fisico
binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: button
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - light.toggle: relay_1

# LED di stato
status_led:
  pin:
    number: GPIO13
    inverted: true