# Pietro Customizations #
substitutions:
  device_name: esp01-th02
  friendly_name: TH-TEMP02
  ip_addres: 192.168.100.42
  platform: esp8266
  board: esp01_1m


# COMMON CONFIG
packages:
  common: !include packages/common.yaml

###################
## DEVICE CONFIG ##
###################
sensor:
  - platform: dht
    pin: 2
    temperature:
      name: "Temperature"
      filters:
        - calibrate_linear:
            - 28.6 -> 18.3
            - 29.4 -> 19.5
        - lambda: |-
            return round(x * 10) / 10.0;
    humidity:
      name: "Humidity"
      filters:
        - calibrate_linear:
            - 31 -> 63
            - 35 -> 68
        - lambda: |-
            return round(x);
    update_interval: 60s
