# Pietro Customizations #
substitutions:
  device_name: esp01-th01
  friendly_name: TH-TEMP01
  ip_addres: 192.168.100.41
  platform: esp8266
  board: esp01_1m


# COMMON CONFIG
packages:
  common: !include packages/common.yaml

###################
## DEVICE CONFIG ##
###################

sensor:
  - platform: dht
    pin: 2
    temperature:
      name: "Temperature"
      filters:
        - calibrate_linear:
            - 25.5 -> 18.8
            - 27.1 -> 19.5
        - lambda: |-
            return round(x * 10) / 10.0;
    humidity:
      name: "Humidity"
      filters:
        - calibrate_linear:
            - 35 -> 63
            - 38 -> 68
        - lambda: |-
            return round(x);
    update_interval: 60s
