# Pietro Customizations #
substitutions:
  device_name: esp01-th04
  place: Cucina
  friendly_name: TH-${place}
  ip_addres: 192.168.100.44
  platform: esp8266
  board: esp01_1m


# COMMON CONFIG
packages:
  common: !include packages/common.yaml

###################
## DEVICE CONFIG ##
###################

sensor:
  - platform: dht
    pin: 2
    temperature:
      name: "Temperatura ${place}"
    humidity:
      name: "Umidità ${place}"
    update_interval: 60s
