# Pietro Customizations #
substitutions:
  device_name: powr3-01
  friendly_name: Generale
  ip_addres: 192.168.100.19
  update_interval: 5s
  platform: esp8266
  board: esp01_1m

# COMMON CONFIG
packages:
  common: !include packages/common.yaml

###################
## DEVICE CONFIG ##
###################

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    internal: True
    on_press:
      - switch.toggle: relay

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 4800
  parity: EVEN

switch:
  - platform: gpio
    name: Power Status
    pin: GPIO12
    inverted: true
    id: relay
    restore_mode: ALWAYS_ON
    internal: True
    

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
  - platform: cse7766
    voltage:
      name: Voltage
      filters:
        - throttle_average: ${update_interval}
    current:
      name: Current
      filters:
        - throttle_average: ${update_interval}
    power:
      name: Power
      filters:
        - throttle_average: ${update_interval}
    energy:
      name: Energy
      filters:
        - throttle_average: ${update_interval}