# Pietro Customizations #
substitutions:
  device_name: plug-p11-02
  friendly_name: P11-02
  ip_addres: 192.168.100.22

# Core Configuration #
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
esp8266:
  board: esp01_1m
time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

# Utility Configuration #
logger:
api:
ota:
  - platform: esphome
captive_portal:
web_server:
  port: 80

# Network Configuration #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: ${ip_addres}
    gateway: 192.168.100.1
    subnet: 255.255.255.0
    dns1: 192.168.100.1
  ap: {}

# Diagnoastic Sensors #
text_sensor:
  - platform: version
    name: ${friendly_name} EspHome Node Version
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${friendly_name} Uptime



###################
## DEVICE CONFIG ##
###################