# Pietro Customizations #
substitutions:
  device_name: s60-01
  friendly_name: S60-01
  ip_addres: 192.168.100.11
  update_interval: 30s

# Core Configuration #
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

# Utility Configuration #
logger:
api:
ota:
  - platform: esphome
captive_portal:
web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_pass

# Network Configuration #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: ${ip_addres}
    gateway: 192.168.100.1
    subnet: 255.255.255.0
    dns1: 192.168.100.1
  ap: {}


###################
## DEVICE CONFIG ##
###################

uart:
  rx_pin: GPIO7
  baud_rate: 4800
  parity: EVEN

status_led:
  pin:
    number: GPIO5
    inverted: False

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "${friendly_name} Status"

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO4
    id: "relay"
    restore_mode: RESTORE_DEFAULT_ON

sensor:
  - platform: cse7766
    voltage:
      name: "${friendly_name} Voltage"
      filters:
        - throttle_average: ${update_interval}
    current:
      name: "${friendly_name} Current"
      filters:
        - throttle_average: ${update_interval}
    power:
      name: "${friendly_name} Power"
      filters:
        - throttle_average: ${update_interval}
    energy:
      name: "${friendly_name} Energy"
      filters:
        - throttle: ${update_interval}
        - multiply: 0.001
      unit_of_measurement: "kWh"
    apparent_power:
      name: "${friendly_name} Apparent Power"
      filters:
        - throttle_average: ${update_interval}
    reactive_power:
      name: "${friendly_name} Reactive Power"
      filters:
        - throttle_average: ${update_interval}
    power_factor:
      name: "${friendly_name} Power Factor"
      filters:
        - throttle_average: ${update_interval}
# Diagnoastic Sensors #

  - platform: wifi_signal
    name: ${device_name}_WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${device_name}_Uptime
text_sensor:
  - platform: version
    name: EspHome Node Version
    hide_timestamp: true