# Pietro Customizations #
substitutions:
  device_name: teckin-sp21-01
  friendly_name: TECKIN SP21
  ip_addres: 192.168.100.11

# Core Configuration #
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
rtl87xx:
  board: generic-rtl8710bn-2mb-788k
time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

# Utility Configuration #
logger:
api:
ota:
  - platform: esphome
captive_portal:
web_server:
  port: 80

# Network Configuration #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: ${ip_addres}
    gateway: 192.168.100.1
    subnet: 255.255.255.0
    dns1: 192.168.100.1
  ap: {}

# Diagnoastic Sensors #
text_sensor:
  - platform: version
    name: ${friendly_name} EspHome Node Version
    hide_timestamp: true
sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${friendly_name} Uptime

###################
## DEVICE CONFIG ##
###################

switch:
  - platform: gpio
    name: "None"
    pin: PA12
    id: relay
    device_class: "outlet"
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - if:
          condition:
            switch.is_on: status_led_config
          then:
            - light.turn_on: blue_led
    on_turn_off:
      - light.turn_off: blue_led
  - platform: template
    name: ${friendly_name} Status LED
    id: status_led_config
    optimistic: true
    entity_category: "config"
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - if:
          condition:
            switch.is_on: relay
          then:
            - light.turn_on: blue_led
    turn_off_action:
      - light.turn_off: blue_led

light:
  - platform: status_led
    id: blue_led
    pin:
      number: PA15
      inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: PA14
    id: button_1
    on_press:
      then:
        - switch.toggle: relay