# Pietro Customizations #
substitutions:
  device_name: template-sonoff-basic-r2
  friendly_name: TEMPLATE-SONOFF-BASIC-R2
  ip_addres: 192.168.100.60

# Core Configuration #
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
esp8266:
  board: esp01_1m
time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

# Utility Configuration #
logger:
api:
ota:
  - platform: esphome
captive_portal:
web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_pass

# Network Configuration #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: ${ip_addres}
    gateway: 192.168.179.1
    subnet: 255.255.255.0
    dns1: 192.168.179.1
  ap: {}

# Diagnoastic Sensors #
text_sensor:
  - platform: version
    name: EspHome Node Version
    hide_timestamp: true
sensor:
  - platform: wifi_signal
    name: ${device_name}_WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${device_name}_Uptime


###################
## DEVICE CONFIG ##
###################

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${device_name}_Button
    on_press:
      - switch.toggle: relay
  - platform: status
    name: ${device_name}_Status

switch:
  - platform: gpio
    name: ${device_name}_Relay
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes