# Pietro Customizations #
substitutions:
  device_name: template-teckin-sp22
  friendly_name: TEMPLATE-TECKIN-SP22
  ip_addres: 192.168.100.63

# Core Configuration #
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
esp8266:
  board: esp8285
time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

# Utility Configuration #
logger:
api:
ota:
  - platform: esphome
captive_portal:
web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_pass

# Network Configuration #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: ${ip_addres}
    gateway: 192.168.179.1
    subnet: 255.255.255.0
    dns1: 192.168.179.1
  ap: {}

# Diagnoastic Sensors #
text_sensor:
  - platform: version
    name: EspHome Node Version
    hide_timestamp: true



###################
## DEVICE CONFIG ##
###################

binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin:
      number: GPIO01
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

switch:
  - id: relay
    platform: gpio
    internal: true
    pin: GPIO14
    on_turn_on:
      - output.turn_on: relay_status
    on_turn_off:
      - output.turn_off: relay_status

status_led:
  pin:
    number: GPIO13
    inverted: true

light:
  - platform: binary
    internal: true
    name: ${device_name}_Relay_Status"
    output: relay_status

output:
  - id: relay_status
    platform: gpio
    pin:
      number: GPIO03
      inverted: true

sensor:
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      name: ${device_name}_Current
    voltage:
      name: ${device_name}_Voltage
    power:
      name: ${device_name}_Power
    energy:
      name: ${device_name}_Energy
    update_interval: 10s
    change_mode_every: 3
# Diagnoastic Sensors #
  - platform: wifi_signal
    name: ${device_name}_WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${device_name}_Uptime