# Pietro Customizations #
substitutions:
  device_name: template-sonoff-mini-buttom
  friendly_name: TEMPLATE-SONOFF-MINI-BUTTON
  ip_addres: 192.168.100.62

# Core Configuration #
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
esp8266:
  board: esp8285
time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

# Utility Configuration #
logger:
api:
ota:
  - platform: esphome
captive_portal:
web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_pass

# Network Configuration #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: ${ip_addres}
    gateway: 192.168.179.1
    subnet: 255.255.255.0
    dns1: 192.168.179.1
  ap: {}

# Diagnoastic Sensors #
text_sensor:
  - platform: version
    name: EspHome Node Version
    hide_timestamp: true
sensor:
  - platform: wifi_signal
    name: ${device_name}_WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: ${device_name}_Uptime


###################
## DEVICE CONFIG ##
###################

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay_1

  - platform: gpio
    name: ${device_name}_status
    pin: GPIO04
    id: switch_1
    on_press:
      then:
        - switch.toggle:
            id: relay_1
    on_release:
      then:
        - switch.toggle:
            id: relay_1

switch:
  - platform: gpio
    name: ${device_name}_switch
    pin: GPIO12
    id: relay_1
    restore_mode: restore_default_off

status_led:
  pin:
    number: GPIO13
    inverted: yes