# Core Configuration #
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.mcu: ${board}
    board_build.variant: ${board}

${platform}:
  variant: ${board}
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

# Utility Configuration #
logger:
  baud_rate: 0
api:
ota:
  - platform: esphome
captive_portal:
web_server:
  port: 80
#external_components:
#  - source: github://TheStaticTurtle/esphome_syslog
#    components: [syslog]
#syslog:
#    ip_address: "192.168.179.11"
#    port: 5514

# Network Configuration #
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: NONE
  manual_ip:
    static_ip: ${ip_addres}
    gateway: 192.168.100.1
    subnet: 255.255.255.0
    dns1: 192.168.100.1
  #ap: {} Disabilitato per ridurre canali wifi in casa


# Diagnoastic Sensors #
sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

text_sensor:
  - platform: version
    name: EspHome Node Version
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: IP

binary_sensor:
  - platform: status
    name: Status
